LPD-X Scan only compileInclude classpath. All dependencies with "Liferay-Require-SchemaVersion" are compileInclude type now. And since d192cf3d56cad846964763021402ada0501633a6, with build.jakarta.transformer.enabled=true, due to the bnd version bump, project dependency on compileClasspath are pointing to classes folder before jaring, causing the following jar reading logic breaking.
* Where:
Build file '/home/trunks/git/liferay-portal/modules/util/portal-tools-sample-sql-builder/build.gradle' line: 115

* What went wrong:
Execution failed for task ':util:portal-tools-sample-sql-builder:writeReleases'.
> java.io.FileNotFoundException: /home/trunks/git/liferay-portal/modules/apps/account/account-api/build/classes/java/main (Is a directory)