LPD-65696 Support launching portal from test code. In this case, both SystemBundleProviderImpl/TestSystemBundleProvider are on the classpath, but the TestSystemBundleProvider is from global classloader, and SystemBundleProvider is from portal webapp classloader, therefore TestSystemBundleProvider won't be able to initialize due to "java.lang.NoClassDefFoundError: com/liferay/portal/kernel/module/util/SystemBundleProvider"